
// This file has been automatically generated by gen_head.lua

using System;
using System.Runtime.InteropServices;

namespace PressureMapper.Linux;

public static partial class UinputConst
{
#pragma warning disable IDE0047

    public const uint UINPUT_MAX_NAME_SIZE = 80;
    public const uint UI_ABS_SETUP = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((4)) << 0) | ((((26))) << ((0 + 8) + 8)));
    public const uint UI_BEGIN_FF_ERASE = (((2U | 1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((202)) << 0) | ((((12))) << ((0 + 8) + 8)));
    public const uint UI_BEGIN_FF_UPLOAD = (((2U | 1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((200)) << 0) | ((((36))) << ((0 + 8) + 8)));
    public const uint UI_DEV_CREATE = (((0U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((1)) << 0) | ((0) << ((0 + 8) + 8)));
    public const uint UI_DEV_DESTROY = (((0U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((2)) << 0) | ((0) << ((0 + 8) + 8)));
    public const uint UI_DEV_SETUP = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((3)) << 0) | ((((92))) << ((0 + 8) + 8)));
    public const uint UI_END_FF_ERASE = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((203)) << 0) | ((((12))) << ((0 + 8) + 8)));
    public const uint UI_END_FF_UPLOAD = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((201)) << 0) | ((((36))) << ((0 + 8) + 8)));
    public const uint UI_GET_VERSION = (((2U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((45)) << 0) | ((((sizeof(uint)))) << ((0 + 8) + 8)));
    public const uint UI_SET_ABSBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((103)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_EVBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((100)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_FFBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((107)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_KEYBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((101)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_LEDBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((105)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_MSCBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((104)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_PHYS = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((108)) << 0) | ((((8))) << ((0 + 8) + 8)));
    public const uint UI_SET_PROPBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((110)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_RELBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((102)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_SNDBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((106)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
    public const uint UI_SET_SWBIT = (((1U) << (((0 + 8) + 8) + 14)) | ((((byte)'U')) << (0 + 8)) | (((109)) << 0) | ((((sizeof(int)))) << ((0 + 8) + 8)));
#pragma warning restore IDE0047
}

